### ISSUE TITLE
Exception in thread "main" org.h2.jdbc.JdbcSQLException: Feature not supported: "server"

### ISSUE THREAD

**Issue by HxRoy** [datatechnology/jraft#1]
why would I find this exception when I run the startsrv.bat

**Comment by datatechnology** [comment]
By default H2LogStore is not used, how do you get this exception?  also, startsrv.bat is used to start a server instance that was killed after addsrv.bat

I tried to replace FileBasedSequentialLogStore with H2LogStore in FileBasedServerStateManager as below, it also works well for me.

> public FileBasedServerStateManager(String dataDirectory){
>        this.logStore = new H2LogStore(dataDirectory);

Please let me know how you reproduce the problem

**Comment by HxRoy** [comment]
Maybe the jar I export is wrong. Now I run it successfully. Thanks.

**Comment by datatechnology** [comment]
Good to hear that
