### ISSUE TITLE
Is this library available in JCenter or Maven Central?

### ISSUE THREAD

**Issue by jjzazuet** [datatechnology/jraft#4]
Like the title asks. I don't think I've found it in Maven Central. Let me know if I can help.

Thanks for an awesome library!

**Comment by datatechnology** [comment]
Oh, hey, sorry for being late, this is not yet published, I can do one, will let you know once it's done

**Comment by jjzazuet** [comment]
@datatechnology thanks!

**Comment by datatechnology** [comment]
Sorry, kind of busy, still working on it, will get this done by this week

**Comment by datatechnology** [comment]
https://search.maven.org/#artifactdetails%7Ccom.github.datatechnology.jraft.core%7Cjraft-core%7C1.0.1%7Cjar
