### ISSUE TITLE
[Question] how could I check leadership

### ISSUE THREAD

**Issue by KimiWu123** [datatechnology/jraft#6]
In our application, we only allow the leader to do tasks or send messages. How could I check current application is leader or not? I can't find methods to achieve that.
Thanks.

**Comment by datatechnology** [comment]
If you use the client, it will redirect all requests to leader, however, if your state machine needs to know the leader, then we should twit it a little bit, and see why

**Comment by KimiWu123** [comment]
In private blockchain, only leader allow to generate blocks if we user raft as our consensus. That's why each server needs to know who having the leadership.

**Comment by datatechnology** [comment]
Understand, however, your server should receive the request from some where else, is that correct? regardless if it's correct or not, you can call handleClientRequest to ask the raft server to process the client request, which will tell in the response who is the leader if the current server is not the leader

See if this helps,

https://github.com/datatechnology/jraft/blob/master/core/src/main/java/net/data/technology/jraft/RaftServer.java#L306

**Comment by KimiWu123** [comment]
Cool! Thanks for your help! 
I'm just wondering why don't you just have a function like getRole/isLeader to check the role of current server?

**Comment by datatechnology** [comment]
Several reasons, 

1. State machine should not have any knowledge about the underlying replication mechamism
2. Even for the state machine, it should always use the RaftClient to append log entries https://github.com/datatechnology/jraft/blob/master/core/src/main/java/net/data/technology/jraft/RaftClient.java
3. There is another way, maybe the simplest one, you may like it https://github.com/datatechnology/jraft/blob/master/core/src/main/java/net/data/technology/jraft/RaftServer.java#L144
