### ISSUE TITLE
Support for StateMachine::preCommit failures

### ISSUE THREAD

**Issue by KalyanAkella** [datatechnology/jraft#8]
Firstly, thanks a lot for this Raft implementation. This is pretty helpful.

I've been building an app using this library and so far I have not found a way for `StateMachine` implementations to throw/report errors from inside `preCommit` method (and also for `commit` and `rollback` methods). I looked up the code and understood how these methods are invoked from inside the `RaftServer` class. Simply throwing `RuntimeException` from these methods is not going to help, since `RaftServer` doesn't have exception handling around these method invocations.

So, here are my thoughts on supporting error reporting + handling for the `preCommit` method:
1. All the 3 invocations of this method inside `RaftServer` class pass the `logIndex` parameter by first appending the entry inside the `SequentialLogStore`.
2. How about appending the log entry inside the `SequentialLogStore` only **after** `preCommit` invocation ? This way, based on how `preCommit` executes (throw checked exception, return value, etc.), we can then either perform the log append or just abort (after any cleanup).
3. This has the potential downside of not passing the `logIndex` parameter to the `preCommit` method but perhaps this might be ok. Or else, we can possibly compute the next offset position in the `SequentialLogStore` for a given `logEntry` and use this as the `logIndex`.

Thoughts ?

**Comment by datatechnology** [comment]
Sorry for missing this, I think Github just sending the email notification to my previous lost email address, will correct this.
the initial idea for having runtime exception is to terminate the process as long as there is anything that the state machine cannot handle. Having the exception before appending the log still can keep safety, would you mind to contribute a pr and we can discuss from there?

**Comment by andy-yx-chen** [comment]
Basically, precommit failure is not required, the application should validate the request before asking raft to replicate the logs, in this point of view, even precommit is not required at all, it's just an extension point
